### ISSUE TITLE
Replace inline numbers with `private static final` constants; Use Double.MIN_VALUE for min double value

### ISSUE THREAD

**Issue by PoslavskySV** [milaboratory/minnn#144]
e.g.

https://github.com/milaboratory/minnn/blob/b5f84a51afcea977155e0a2be2006204a2c2bb26/src/main/java/com/milaboratory/minnn/io/ConsensusIO.java#L933

**Comment by Alexander230** [comment]
Double.MIN_VALUE must not be used here, it is overflow protection

**Comment by Alexander230** [comment]
Done in https://github.com/milaboratory/minnn/tree/feature/consensus-stats
