### ISSUE TITLE
Move leftCut and rightCut in FuzzyMatchPattern to a separate class (upper level)

### ISSUE THREAD

**Issue by dbolotin** [milaboratory/minnn#44]
Discussion required

**Comment by dbolotin** [comment]
?

**Comment by Alexander230** [comment]
Moving cuts to separate class is not effective: alignment is needed for scoring, and sorting by score is needed for output matches. Moving cuts to separate class will require to create multiple FuzzyMatchPattern objects for each combination of left and right cuts. Current implementation stores all that combinations as array of patterns inside FuzzyMatchPattern, and this allows more convenient sorting of output matches by score.
